// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itrppphvoplivrosjmoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cnBwcGh2b3BsaXZyb3NqbW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDcwMjQsImV4cCI6MjA3NDUyMzAyNH0.zXoaYaapFhRS78MX11ndOHsP2WszFSLSpdmALapn2FQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});